name: GraalVM Native Image build

on: push

jobs:
  nativeImage:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['22.0.0.2']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-build-action@v2
      - name: install dependencies
        run: |
          sudo apt install upx libxi-dev libxt-dev libgles-dev libgl-dev
      - name: Build native image
        run: |
          ./gradlew build nativeImage
          upx build/bin/ebviewer
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ebviewer-${{ matrix.os }}
          path: build/bin/*